apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: token-db-backup
  namespace: openclaw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
