apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: openclaw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
