apiVersion: v1
kind: Service
metadata:
  name: gmail-mcp-remote-funnel
  namespace: openclaw
  labels:
    app: gmail-mcp-remote
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/funnel: "true"
    tailscale.com/hostname: "gmail-mcp"
spec:
  type: ClusterIP
  selector:
    app: gmail-mcp-remote
  ports:
    - port: 443
      targetPort: 8002
      protocol: TCP
# Once running, this service is reachable at:
#   https://gmail-mcp.<tailnet-name>.ts.net
# Use this as GMAIL_BASE_URL in config.env
