apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gmail-mcp-data
  namespace: openclaw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
