apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkedin-scheduler-data
  namespace: openclaw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
